
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A CONECTAR FUENTE ID NUMERO OPERADOR REPLICAS SIMULAR SUMIDERO TIEMPO_SERVICIOprograma : instruccionesinstrucciones : instrucciones instruccioninstrucciones : instruccioninstruccion : FUENTE IDinstruccion : OPERADOR ID TIEMPO_SERVICIO NUMEROinstruccion : OPERADOR ID TIEMPO_SERVICIO NUMERO REPLICAS NUMEROinstruccion : SUMIDERO IDinstruccion : CONECTAR ID A IDinstruccion : SIMULAR NUMERO'
    
_lr_action_items = {'FUENTE':([0,2,3,9,10,12,14,17,18,20,],[4,4,-3,-2,-4,-7,-9,-5,-8,-6,]),'OPERADOR':([0,2,3,9,10,12,14,17,18,20,],[5,5,-3,-2,-4,-7,-9,-5,-8,-6,]),'SUMIDERO':([0,2,3,9,10,12,14,17,18,20,],[6,6,-3,-2,-4,-7,-9,-5,-8,-6,]),'CONECTAR':([0,2,3,9,10,12,14,17,18,20,],[7,7,-3,-2,-4,-7,-9,-5,-8,-6,]),'SIMULAR':([0,2,3,9,10,12,14,17,18,20,],[8,8,-3,-2,-4,-7,-9,-5,-8,-6,]),'$end':([1,2,3,9,10,12,14,17,18,20,],[0,-1,-3,-2,-4,-7,-9,-5,-8,-6,]),'ID':([4,5,6,7,16,],[10,11,12,13,18,]),'NUMERO':([8,15,19,],[14,17,20,]),'TIEMPO_SERVICIO':([11,],[15,]),'A':([13,],[16,]),'REPLICAS':([17,],[19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> instrucciones','programa',1,'p_programa','parser.py',11),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones_multiple','parser.py',15),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_una','parser.py',19),
  ('instruccion -> FUENTE ID','instruccion',2,'p_instruccion_fuente','parser.py',23),
  ('instruccion -> OPERADOR ID TIEMPO_SERVICIO NUMERO','instruccion',4,'p_instruccion_operador','parser.py',30),
  ('instruccion -> OPERADOR ID TIEMPO_SERVICIO NUMERO REPLICAS NUMERO','instruccion',6,'p_instruccion_operador_replicas','parser.py',37),
  ('instruccion -> SUMIDERO ID','instruccion',2,'p_instruccion_sumidero','parser.py',44),
  ('instruccion -> CONECTAR ID A ID','instruccion',4,'p_instruccion_conectar','parser.py',51),
  ('instruccion -> SIMULAR NUMERO','instruccion',2,'p_instruccion_simular','parser.py',58),
]
